build:
  nodes:
    meedu-test:
      # 测试环境
      environment:
        php:
          version: 7.1.12
          pecl_extensions:
            - redis

      # 缓存，加快速度
      cache:
        directories:
          - ~/.composer/cache

      # 测试需要的服务
      services:
        mysql: 5.6
        redis: 4

      # 依赖
      dependencies:
        before:
          - mysql -e 'create database if not exists meedu;'
          - cp .env.testing .env
          - php artisan key:generate

      # 测试
      tests:
        override:
          - command: ./vendor/bin/phpunit --coverage-clover=coverage.xml
              coverage:
                file: coverage.xml
                format: php-clover