version: '2.2'
services:
  php:
    container_name: "meeduphp"
    build:
      context: ./docker
    volumes:
      - .:/var/www/html/:rw
    restart: always
    expose:
      - "9000"
    networks:
      - meedu-net

  nginx:
    container_name: "meedunginx"
    image: nginx:1.15.7
    ports:
      - "9006:80"
      - "443:443"
    volumes:
      - .:/var/www/html/:rw
      - ./docker/nginx/conf.d:/etc/nginx/conf.d/:rw
      - ./docker/nginx/logs:/var/log/nginx/:rw
      - ./docker/nginx/ssl:/etc/nginx/ssl
    restart: always
    networks:
      - meedu-net

  mysql:
    container_name: "meedumysql"
    image: mysql:5.6
    expose:
      - "3306"
    volumes:
      - ./docker/mysql/conf:/etc/mysql/conf.d/:rw
      - ./docker/mysql/logs:/logs/:rw
      - ./docker/mysql/data:/var/lib/mysql/:rw
    restart: always
    networks:
     - meedu-net
    environment:
      - MYSQL_ROOT_PASSWORD="123456"

networks:
  meedu-net:
    external: true
